services:
  - type: web
    name: sanatan-trust
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
